# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'p2hacks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.11.0'
  # Pods for p2hacks

  target 'p2hacksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'p2hacksUITests' do
    # Pods for testing
  end

end
